### PR TITLE
Running zsh tests on Travis CI

### PR DESCRIPTION
**Pull request by umireon**
Ensure the integration tests executed with zsh and sh (dash) on Travis CI.

### CODE REVIEW

**Comment by DhavalKapil** [comment]
Any reason why `sh` shell is unable to parse https://github.com/DhavalKapil/luaver/blob/master/luaver#L265 in this particular code whereas it is working fine in other branches?

**Comment by umireon** [comment]
dash (and POSIX-sh) does not support arrays.

**Comment by DhavalKapil** [comment]
Then why is it running fine in https://travis-ci.org/DhavalKapil/luaver/jobs/185403585 ?

**Comment by umireon** [comment]
Every job actually tests against bash. No zsh or sh (dash) testing are performed on Travis CI.

**Comment by DhavalKapil** [comment]
I get your point. And this PR ensures that the tests run on zsh and sh?

**Comment by umireon** [comment]
Yes!

**Pull request merged**
